cc_library(
    name = "tetris_if",
    srcs = ["tetris.cpp",
            "tetris.h"],
    deps = [
        "@ncurses//:ncurses_headers",
        "@ncurses",
    ],
    visibility = ["//visibility:public"],  # allows main.cpp to use it
)